package com.fidroid.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEST".
 */
public class Test {

    private Long id;
    private String name;
    private String project;

    public Test() {
    }

    public Test(Long id) {
        this.id = id;
    }

    public Test(Long id, String name, String project) {
        this.id = id;
        this.name = name;
        this.project = project;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProject() {
        return project;
    }

    public void setProject(String project) {
        this.project = project;
    }

}
